#
# DAL upgrade script for CentOS 7
# Copyright (c) 2023, Diversity Arrays Technology, All rights reserved.
#
# Author: Puthick Hok
# Date: 16/03/2018
# Usage: ansible-playbook kddart_dal_upgrade_v2_4_0_to_v2_5_0_centos7_from_file.yml
# Description: By running the usage command, ansible will install and configure DAL
#              according the instructions in kddart_dal_upgrade_v2_4_0_to_v2_5_0_centos7.yml.
#              This script can be run by root or a root super user which can do sudo without password.
#              For more information about how to read and write an ansible playbook,
#              please refer to ansible documentation on the web.
#

- hosts: kddartserver
  gather_facts: yes

  vars_prompt:
    - name: "local_tar_gz_file"
      prompt: "Enter the source tar.gz file of KDDart wih either relative or full path."
      private: no

  vars:
    dal_version: v2.7.0
    dal_db_version: v2_7_0
    src_file: /root/KDDArT-DAL-{{ dal_version }}.tar.gz
    old_dal_db_version: v2_6_0
    local_dir: /root/KDDArT-DAL-{{ dal_version }}
    backup_dir: /root/dal_upgrade_db_backup
    apache_base_dir: /var/www
    solr_home: /var/solr
    force_tasks: True

  tasks:

    - name: Copy the tar.gz file
      copy: src={{ local_tar_gz_file }} dest={{ src_file }}

    - name: Create local_dir
      shell: "[[ -d {{ local_dir }} ]] || mkdir {{ local_dir }}"

    - name: Untar and decompress KDDart source
      shell: >
        if [ -d {{ local_dir }} ]; then
        cd {{ local_dir }};
        tar --no-same-owner -zxvf {{ src_file }} --strip 1;
        fi;

    - import_tasks: ./kddart_dal_upgrade_v2_6_0_to_v2_7_0_centos7.yml
      static: yes
